apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitea
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitea
    spec:
      containers:
      - image: quay.io/sfhassan/gitea:1.21.11-rootless
        name: gitea
        env:
        - name: "GITEA__security__INSTALL_LOCK"
          value: "true"
            #        command:
            #          - /bin/sh
            #          - -c 
            #          - "gitea admin user create --admin --username syed --password syed1234 --email syed@example.com; while true; do sleep 100; done" 
      volumeMounts:
      - name: gitea-config
        mountPath: /etc/gitea
      - name: gitea-data
        mountPath: /var/lib/gitea 
          #           "gitea admin user create --admin --username syed --password syed1234 --email syed@example.com -c /data/gitea/conf/app.ini"
    volumes:
    - name: gitea-data
      persistentVolumeClaim:
        claimName: gitea-data-pvc
    - name: gitea-config
      persistentVolumeClaim:
        claimName: gitea-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: giteahttp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: giteahttp
  - port: 2222
    protocol: TCP
    targetPort: 2222
    name: giteassh
  selector:
    app: gitea
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gitea
  name: giteahttp
spec:
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    kind: ""
    name: giteahttp
    weight: null
