== What is Gitea: 
Gitea is an opensource Git server, available at: https://about.gitea.com/ 

== Gitea in Kubernetes
Though their site provides some pointers about how to run it in a docker contatiner, I didn't find good instructions and sample manifests to run Gitea in a Kubernetes environment 
This repo is meant to provide a [!full manifest](https://github.com/git-shassan/Gitea/tree/main/gitea_full.yaml) that can be used for that purpose, as well as a breakdown of the manifest to explain any changes you may need to make for your own environment.

== The steps: 

=== Step#1: Creating PVC:
Gitea uses two volume mount points. The example here assumes that you have Persistent Volume configured, that uses storage class `ocs-storagecluster-ceph-rbd`. 
However, other storageclass may be used. If you don't have a persistent volume, you can always skip this step and use `emptydir` later when creating the deploloyment. However, that will ofcourse not offer your persistent storage. 

The size of the PVC here are not based on any recommendations. So adjusst these based on your requirements.  (1G might be overkill for  config mount, and 8G may not be sufficient for some deployments) 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
```
=== Step#2: Creating Deployment:
This step simply creates the deployment. The only mentionable step here is use of the environment variable `GITEA__security__INSTALL_LOCK`. Any environment varibale passed to Gitea pod in this format are used to set up the initializtion files in Gitea. More details are available [here](https://docs.gitea.com/installation/install-with-docker-rootless#managing-deployments-with-environment-variables) 

The only variable being passed here is `INSTALL_LOCK` that goes under the `security` section of the app.ini configuration file. This removes the need to manually perform the initial installation. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitea
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitea
    spec:
      containers:
      - image: quay.io/sfhassan/gitea:1.21.11-rootless
        name: gitea
        env:
        - name: "GITEA__security__INSTALL_LOCK"
          value: "true"
      volumeMounts:
      - name: gitea-config
        mountPath: /etc/gitea
      - name: gitea-data
        mountPath: /var/lib/gitea 
    volumes:
    - name: gitea-data
      persistentVolumeClaim:
        claimName: gitea-data-pvc
    - name: gitea-config
      persistentVolumeClaim:
        claimName: gitea-config-pvc
```
                                                                                                             
=== Step#3: Creating Service and Routes:
By default, Gitea is lisening on port 3000 for http, and 2222 for ssh. So use these to define a service and a route: 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: giteahttp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: giteahttp
  - port: 2222
    protocol: TCP
    targetPort: 2222
    name: giteassh
  selector:
    app: gitea
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gitea
  name: giteahttp
spec:
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    kind: ""
    name: giteahttp
    weight: null

```
                                                                                                   
=== Step#4: Creating User:
unfortunately, this step can't yet be done through manifests. The commands in manifests are executed BEFORE the environment variable takes affect, so they fail. However if we just pass the environment variable , then there is  no option but to manually configure the user details. 
This is done by attaching to the pod, e.g: 
```
oc exec -it -n default gitea-56f66586cf-kbk76 -- /bin/bash
```

Then run a command like this one: 
```
gitea admin user create --admin --username syed --password syed1234 --email syed@example.com
```

== Done: 
At this point, Gitea should be up and running, and accessing using the URL shown here: 
```
c get routes.route.openshift.io 
NAME        HOST/PORT                                  PATH   SERVICES    PORT   TERMINATION   WILDCARD
giteahttp   giteahttp-gitea.apps.mgmt1.npss.bos2.lab          giteahttp   3000   edge          None

```

                                                                                                              
                                                                                                              
                                                                                                              
                                                                                                              
                                                                                                              
